lms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path

from students.views import hello


urlpatterns = [
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers2.urls')),
    path('', include('core.urls')),

    path('admin/', admin.site.urls),
    path('hello/', hello),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import create_student, delete_student, edit_student, generate_students, get_students

app_name = 'students'

urlpatterns = [
    path('generate/', generate_students, name='generate'),
    path('', get_students, name='list'),
    path('create/', create_student, name='create'),
    path('edit/<uuid:uuid>', edit_student, name='edit'),
    path('delite/<uuid:uuid>', delete_student, name='delete'),
]

students/models.py
import datetime

from core.models import Persona

from django.db import models

from groups.models import Group


class Students(Persona):
    # uuid = models.TextField(null=False)
    # first_name = models.CharField(max_length=64, null=False)
    # last_name = models.CharField(max_length=84, null=False)
    birthdate = models.DateTimeField(null=True, default=datetime.date.today)
    rating = models.SmallIntegerField(null=True, default=0)
    phone_number = models.TextField(null=True, max_length=12)
    group = models.ForeignKey(
        to=Group,
        null=True,
        on_delete=models.SET_NULL,
        related_name='students'
    )

    # def full_name(self):
    #     return f'{self.first_name}, {self.last_name}'

    def age(self):
        return datetime.datetime.now().date().year - self.birthdate.year

    def __str__(self):
        return f'{super().__str__()}, {self.age()}, {self.rating}, {self.phone_number}'

students/forms.py
from django import forms
from django.http import HttpResponse

from students.models import Students


class StudentsCreateForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = ['first_name', 'last_name', 'rating', 'phone_number', 'group']

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']

        if phone_number is None:
            raise ValueError("ERROR: indicate the phone number")
        if not phone_number.isdigit():
            raise ValueError("VALUE ERROR: only digital values")

        try:
            return phone_number
        except Exception as ex:
            return HttpResponse(str(ex), status_code=400)

students/views.py
from uuid import uuid4

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from faker import Faker

from students.forms import StudentsCreateForm
from students.models import Students
from students.utils import get_count, padding_fake_data_students

fake = Faker()


def hello(request):
    return HttpResponse('Hello from Django')


def generate_students(request):
    try:
        count = get_count(request)
    except Exception as ex:
        return HttpResponse(str(ex), status_code=400)
    padding_fake_data_students(count)

    return HttpResponseRedirect(reverse('students:list'))


def get_students(request):
    students = Students.objects.select_related('group').all()

    first_name = request.GET.get('first_name')
    last_name = request.GET.get('last_name')
    rating = request.GET.get('rating')
    phone_number = request.GET.get('phone_number')

    if first_name:
        students = students.filter(first_name=first_name)
    if last_name:
        students = students.filter(last_name=last_name)
    if rating:
        students = students.filter(rating=rating)
    if phone_number:
        students = students.filter(phone_number=phone_number)

    return render(
        request=request,
        template_name='students-list.html',
        context={
            'students': students,
        }
    )


def create_student(request):

    if request.method == 'GET':
        form = StudentsCreateForm()

    elif request.method == 'POST':
        form = StudentsCreateForm(request.POST)
        if form.is_valid():
            form.save()
            st = Students.objects.last()
            st.uuid = uuid4()
            st.save()
            return HttpResponseRedirect(reverse('students:list'))

    return render(
        request=request,
        template_name='students-create.html',
        context={
            'form': form,
        }
    )


def edit_student(request, uuid):
    try:
        student = Students.objects.get(uuid=uuid)
    except Students.DoesNotExist:
        return HttpResponse("Student doesn`t exist", status=404)

    if request.method == 'GET':
        form = StudentsCreateForm(instance=student)

    elif request.method == 'POST':
        form = StudentsCreateForm(
            data=request.POST,
            instance=student
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:list'))

    return render(
        request=request,
        template_name='students-edit.html',
        context={
            'form': form,
            'student': student
        }
    )


def delete_student(request, uuid):
    student = get_object_or_404(Students, uuid=uuid)
    student.delete()

    return HttpResponseRedirect(reverse('students:list'))

students/templates/students-create.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block title %}
    <title>Create student</title>
{% endblock %}

{% block header %}
    <h1>Create student</h1>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        {{form|crispy}}

      <input class="btn btn-success" type="submit" value="Create">
    </form>
{% endblock %}

students/templates/students-edit.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block title %}
    <title>Edit Student</title>
{% endblock %}

{% block header %}
    <h1>Edit Student</h1>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        {{form|crispy}}

      <input class="btn btn-success" type="submit" value="Save">
      <input class="btn btn-danger" formaction="{% url 'students:delete' student.uuid %}" type="submit" value="Delete">
    </form>

{% endblock %}

students/templates/students-list.html
{% extends 'base.html'%}

{% block title %}
    <title>Students list</title>
{% endblock %}

{% block header %}
    <h1>Students list</h1>
{% endblock %}

{% block content %}
    <form>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">First name</span>
            </div>
            <input name="first_name" type="text" class="form-control" placeholder="Enter first name" aria-label="Username" aria-describedby="basic-addon1">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon2">Last name</span>
            </div>
            <input name="last_name" type="text" class="form-control" placeholder="Enter last name" aria-label="Username" aria-describedby="basic-addon1">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon3">Rating:</span>
            </div>
            <input name="rating" type="number" class="form-control" placeholder="Enter rating" aria-label="Username" aria-describedby="basic-addon1">
        </div>

         <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon4">Phone Number:</span>
            </div>
            <input name="phone_number" type="number" class="form-control" placeholder="Enter phone number" aria-label="Username" aria-describedby="basic-addon1">
        </div>

      <div class="mb-3">
          <input class="btn btn-primary" type="submit" value="Search">
          <input class="btn btn-success" formaction="{% url 'students:create' %}" type="submit" value="Create">
      </div>
    </form>


    {% include 'includes/students-table.html' %}

{% endblock %}