groups/urls.py
from django.urls import path

from groups.views import create_group, delete_group, edit_group, generate_groups, get_groups

app_name = 'groups'

urlpatterns = [
    path('create/', create_group, name='create'),
    path('delete/<uuid:uuid>', delete_group, name='delete'),
    path('generate/', generate_groups, name='generate'),
    path('edit/<uuid:uuid>', edit_group, name='edit'),
    path('', get_groups, name='list'),

]

lms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path

from students.views import hello


urlpatterns = [
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers2.urls')),
    path('', include('core.urls')),

    path('admin/', admin.site.urls),
    path('hello/', hello),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

groups/models.py
import datetime

from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from teachers2.models import Teacher


class Classroom(models.Model):
    name = models.CharField(max_length=32)
    floor = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(2), MaxValueValidator(5)]
    )

    def __str__(self):
        return f'{self.name}, {self.floor}'


class Group(models.Model):
    uuid = models.TextField(null=False)
    first_name = models.CharField(max_length=64, null=False)
    last_name = models.CharField(max_length=84, default='---')
    birthdate = models.DateTimeField(null=True, default=datetime.date.today)
    course = models.CharField(max_length=84, null=False)
    classrooms = models.ManyToManyField(
        to=Classroom,
        related_name='groups'
    )
    teacher = models.ForeignKey(
        to=Teacher,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups'
    )
    head = models.OneToOneField(
        to='students.Students',
        null=True,
        on_delete=models.SET_NULL,
        related_name='head_of_group'
    )

    def __str__(self):
        return f'{self.id}{self.first_name}, {self.course}'

    def clean(self):
        gr = Group.objects.get(id=self.id)
        group_students = gr.students.all()
        if self.head not in group_students:
            raise ValidationError("Студент не входи в состав группы")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

groups/forms.py
from django import forms

from groups.models import Group


class GroupsCreateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['first_name', 'course', 'teacher', 'head', 'classrooms']

groups/views.py
from uuid import uuid4

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from groups.forms import GroupsCreateForm
from groups.models import Group
from groups.utils import padding_fake_data_groups

from students.utils import get_count


def get_groups(request):
    groups = Group.objects.select_related('teacher').all()
    first_name = request.GET.get('first_name')
    course = request.GET.get('course')

    if first_name:
        groups = groups.filter(first_name=first_name)
    if course:
        groups = groups.filter(last_name=course)

    return render(
            request=request,
            template_name='groups-list.html',
            context={
                'groups': groups
            }
        )


def generate_groups(request):
    try:
        count = get_count(request)
    except Exception as ex:
        return HttpResponse(str(ex), status_code=400)
    padding_fake_data_groups(count)
    return HttpResponseRedirect(reverse('groups:list'))


def create_group(request):
    if request.method == 'GET':
        form = GroupsCreateForm()
    elif request.method == 'POST':
        form = GroupsCreateForm(request.POST)
        if form.is_valid():
            form.save()
            gr = Group.objects.last()
            gr.uuid = uuid4()
            gr.save()
            return HttpResponseRedirect(reverse('groups:list'))
    return render(
        request=request,
        template_name='groups-create.html',
        context={
            'form': form
        }
    )


def edit_group(request, uuid):
    try:
        group = Group.objects.get(uuid=uuid)
    except Group.DoesNotExist:
        return HttpResponse("Group doesn`t exist", status=404)

    if request.method == 'GET':
        form = GroupsCreateForm(instance=group)
    elif request.method == 'POST':
        form = GroupsCreateForm(
            data=request.POST,
            instance=group
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groups:list'))

    return render(
        request=request,
        template_name='groups-edit.html',
        context={
            'form': form,
            'group': group,
            'students': group.students.all()
        }
    )


def delete_group(request, uuid):
    group = get_object_or_404(Group, uuid=uuid)
    group.delete()

    return HttpResponseRedirect(reverse('groups:list'))

groups/templates/groups-create.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block title %}
    <title>Create group</title>
{% endblock %}

{% block header %}
    <h1>Create group</h1>
{% endblock %}


{% block content %}
    <form method="post">
        {% csrf_token %}

        {{form|crispy}}
     <input class="btn btn-success" type="submit" value="Create">
    </form>
{% endblock %}

groups/templates/groups-edit.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block title %}
    <title>Edit group</title>
{% endblock %}

{% block header %}
    <h1>Edit group</h1>
{% endblock %}


{% block content %}
    <form method="post">
        {% csrf_token %}

        {{form|crispy}}
     <input class="btn btn-success mb-3"  type="submit" value="Save">
     <input class="btn btn-danger mb-3" formaction="{% url 'groups:delete' group.uuid %}" type="submit" value="Delete">
    </form>

    {% include 'includes/students-table.html' %}

{% endblock %}

groups/templates/groups-list.html
{% extends 'base.html'%}

{% block title %}
    <title>Groups list</title>
{% endblock %}

{% block header %}
    <h1>Groups list</h1>
{% endblock %}


{% block content %}
    <form>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Group name</span>
            </div>
            <input name="first_name" type="text" class="form-control" placeholder="Enter group name" aria-label="Username" aria-describedby="basic-addon1">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon2">Course</span>
            </div>
            <input name="last_name" type="text" class="form-control" placeholder="Enter course" aria-label="Username" aria-describedby="basic-addon1">
        </div>

      <input class="btn btn-primary" type="submit" value="Search">
      <input class="btn btn-success" formaction="{% url 'groups:create' %}" type="submit" value="Create"><br><br>
    </form>

{% include 'includes/groups-table.html' %}

{% endblock %}