lms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path

from students.views import hello


urlpatterns = [
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers2.urls')),
    path('', include('core.urls')),

    path('admin/', admin.site.urls),
    path('hello/', hello),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

teachers2/urls.py
from django.urls import path

from teachers2.views import create_teacher, delete_techear, edit_teacher, generate_teachers, get_teachers

app_name = 'teachers'

urlpatterns = [
    path('generate/', generate_teachers, name='generate'),
    path('', get_teachers, name='list'),
    path('create/', create_teacher, name='create'),
    path('edit/<uuid:uuid>', edit_teacher, name='edit'),
    path('delete/<uuid:uuid>', delete_techear, name='delete'),
]

teachers2/models.py
import datetime

from core.models import Persona

from django.db import models


class Teacher(Persona):
    # uuid = models.TextField(null=False)
    # first_name = models.CharField(max_length=64, null=False)
    # last_name = models.CharField(max_length=84, null=False)
    birthdate = models.DateTimeField(null=True, default=datetime.date.today)
    rating = models.SmallIntegerField(null=True, default=0)
    certification_date = models.DateField(null=True, default=datetime.date.today)
    email = models.EmailField(null=True, max_length=128)

    # def full_name(self):
    #     return f'{self.first_name}, {self.last_name}'

    def other_information(self):
        return f'{self.rating}, {self.certification_date}, {self.email}'

    def __str__(self):
        return f'{self.id}, {super().__str__()}, {self.other_information()}'

teachers2/forms.py
from django import forms

from teachers2.models import Teacher


class TeacherCreateForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'rating', 'email']

teachers2/views.py
from uuid import uuid4

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from students.utils import get_count

from teachers2.forms import TeacherCreateForm
from teachers2.models import Teacher
from teachers2.utils import padding_fake_data_teachers


def get_teachers(request):
    teachers = Teacher.objects.all()
    params = [
        "first_name",
        "last_name",
        "rating"
    ]
    for param in params:
        value = request.GET.get(param)
        if value:
            teachers = teachers.filter(**{param: value})
    return render(
        request=request,
        template_name='teachers-list.html',
        context={
            'teachers': teachers
        }
    )


def generate_teachers(request):
    try:
        count = get_count(request)
    except Exception as ex:
        return HttpResponse(str(ex), status_code=400)
    padding_fake_data_teachers(count)
    return HttpResponse("Ok")


def create_teacher(request):
    if request.method == 'GET':
        form = TeacherCreateForm()

    elif request.method == 'POST':
        form = TeacherCreateForm(request.POST)
        if form.is_valid():
            form.save()
            th = Teacher.objects.last()
            th.uuid = uuid4()
            th.save()
            return HttpResponseRedirect(reverse('teachers:list'))

    return render(
        request=request,
        template_name='teachers-create.html',
        context={
            'form': form
        }
    )


def edit_teacher(request, uuid):
    try:
        teacher = Teacher.objects.get(uuid=uuid)
    except Teacher.DoesNotExist:
        return HttpResponse("Student doesn`t exist", status=404)

    if request.method == 'GET':
        form = TeacherCreateForm(instance=teacher)

    elif request.method == 'POST':
        form = TeacherCreateForm(
            data=request.POST,
            instance=teacher
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:list'))

    return render(
        request=request,
        template_name='teachers-edit.html',
        context={
            'form': form,
            'teacher': teacher,
            'groups': teacher.groups.all()
        }
    )


def delete_techear(request, uuid):
    teacher = get_object_or_404(Teacher, uuid=uuid)
    teacher.delete()
    return HttpResponseRedirect(reverse('teachers:list'))

teachers2/templates/teachers-create.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block title %}
    <title>Create teacher</title>
{% endblock %}

{% block header %}
    <h1>Create teacher</h1>
{% endblock %}


{% block content %}
    <form method="post">
        {% csrf_token %}

        {{form|crispy}}

      <input class="btn btn-success" type="submit" value="Create">
    </form>
{% endblock %}

teachers2/templates/teachers-edit.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}


{% block title %}
    <title>Edit teacher</title>
{% endblock %}

{% block header %}
    <h1>Edit teacher</h1>
{% endblock %}


{% block content %}
    <form method="post">
        {% csrf_token %}

        {{form|crispy}}

        <input class="btn btn-success mb-3" type="submit" value="Save">
        <input class="btn btn-danger mb-3" formaction="{% url 'teachers:delete' teacher.uuid %}" type="submit" value="Delete">
    </form>

{% include 'includes/groups-table.html' %}

{% endblock %}

teachers2/templates/teachers-list.html
{% extends 'base.html'%}

{% block title %}
    <title>Teachers list</title>
{% endblock %}

{% block header %}
    <h1>Teachers list</h1>
{% endblock %}


{% block content %}
    <form>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">First name</span>
            </div>
            <input name="first_name" type="text" class="form-control" placeholder="Enter first name" aria-label="Username" aria-describedby="basic-addon1">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon2">Last name</span>
            </div>
            <input name="last_name" type="text" class="form-control" placeholder="Enter last name" aria-label="Username" aria-describedby="basic-addon1">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon3">Rating:</span>
            </div>
            <input name="rating" type="number" class="form-control" placeholder="Enter rating" aria-label="Username" aria-describedby="basic-addon1">
        </div>

         <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon4">Email:</span>
            </div>
            <input name="email" type="number" class="form-control" placeholder="Enter email" aria-label="Username" aria-describedby="basic-addon1">
        </div>

      <input class="btn btn-primary" type="submit" value="Search">
      <input class="btn btn-success" formaction="{% url 'teachers:create' %}" type="submit" value="Create"><br><br>
    </form>

    <table class="table table-striped table-dark">
        <tr>
            <th>Edit</th>
            <th>ID</th>
            <th>Teacher First Name</th>
            <th>Teacher Last Name</th>
            <th>Rating</th>
            <th>Email</th>
            <th>Certification date</th>
        </tr>
    {% for teacher in teachers %}
        <tr>
            <td><a href="{% url 'teachers:edit' teacher.uuid %}">EDIT✎</a></td>
            <td>{{ teacher.id }}</td>
            <td>{{ teacher.first_name }}</td>
            <td>{{ teacher.last_name }}</td>
            <td>{{ teacher.rating }}</td>
            <td>{{ teacher.email }}</td>
            <td>{{ teacher.certification_date }}</td>
        </tr>
    {% endfor %}
    </table>

{% endblock %}