core/urls.py
from core.views import index

from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

groups/urls.py
from django.urls import path

from groups.views import create_group, delete_group, edit_group, generate_groups, get_groups

app_name = 'groups'

urlpatterns = [
    path('create/', create_group, name='create'),
    path('delete/<uuid:uuid>', delete_group, name='delete'),
    path('generate/', generate_groups, name='generate'),
    path('edit/<uuid:uuid>', edit_group, name='edit'),
    path('', get_groups, name='list'),

]

lms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path

from students.views import hello


urlpatterns = [
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers2.urls')),
    path('', include('core.urls')),

    path('admin/', admin.site.urls),
    path('hello/', hello),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import create_student, delete_student, edit_student, generate_students, get_students

app_name = 'students'

urlpatterns = [
    path('generate/', generate_students, name='generate'),
    path('', get_students, name='list'),
    path('create/', create_student, name='create'),
    path('edit/<uuid:uuid>', edit_student, name='edit'),
    path('delite/<uuid:uuid>', delete_student, name='delete'),
]

teachers2/urls.py
from django.urls import path

from teachers2.views import create_teacher, delete_techear, edit_teacher, generate_teachers, get_teachers

app_name = 'teachers'

urlpatterns = [
    path('generate/', generate_teachers, name='generate'),
    path('', get_teachers, name='list'),
    path('create/', create_teacher, name='create'),
    path('edit/<uuid:uuid>', edit_teacher, name='edit'),
    path('delete/<uuid:uuid>', delete_techear, name='delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% block title %}
    <title>LMS</title>
{% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">

    <a class="navbar-brand" href="{% url 'core:index' %}">LMS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'students:list' %}">Students<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'groups:list' %}">Groups<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'teachers:list' %}">Teachers<span class="sr-only">(current)</span></a>
        </li>

      </ul>

    </div>
  </div>
</nav>

  <div class="container">

    <div class="border shadow m-3 bg-light rounded text-center">
      {% block header %}
          <h1>Welkome to LMS!</h1>
      {% endblock %}
    </div>

    {% block content %}
    {% endblock %}

  </div>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<!--<ul>-->
<!--    <li><a href="{% url 'students:list' %}">Students list</a></li>-->
<!--    <li><a href="{% url 'groups:list' %}">Groups list</a></li>-->
<!--    <li><a href="{% url 'teachers:list' %}">Teachers list</a></li>-->
<!--</ul>-->
{% endblock %}